export const FETCH_TOPIMAGE = "FETCH_TOPIMAGE"
export const FETCH_PAGE_BY_PATH = "FETCH_PAGE_BY_PATH"
export const FETCH_TOPNAV = "FETCH_TOPNAV"
export const FETCH_PAGES = "FETCH_PAGES"
export const UPDATE_EDITOR_STATE = "UPDATE_EDITOR_STATE"

