export const FETCH_PAGE_TEXT_BY_PATH = "FETCH_PAGE_TEXT_BY_PATH"
export const FETCH_KEY_BY_PATH = "FETCH_KEY_BY_PATH"
export const FETCH_PAGE_TEXT_BY_TITLE = "FETCH_PAGE_TEXT_BY_TITLE"
export const FETCH_PAGE_BY_PATH = "FETCH_PAGE_BY_PATH"

export const FETCH_TOPIMAGE = "FETCH_TOPIMAGE"
export const FETCH_TOPNAV = "FETCH_TOPNAV"
export const FETCH_PAGES = "FETCH_PAGES"
export const FETCH_CONTACT = "FETCH_CONTACT"
export const FETCH_USER = "FETCH_USER";

export const UPDATE_EDITOR_STATE = "UPDATE_EDITOR_STATE"
